### ISSUE TITLE
Add support for opening/closing tag --{ and }--

### ISSUE THREAD

**Issue by kevin39** [martin-damien/language-smarty-php#2]
My project is using --{ and }-- as Smarty tags.

It will be great to set opening/closing tag as configurable settings.

Is there anything I can do to get syntax coloring to work properly in my case ?

**Comment by martin-damien** [comment]
Hi @kevin39 

Just to inform you that this issue will not be fixed for the simple reason that I will delete the package.

You should use https://atom.io/packages/language-smarty package, it looks to be maintained (last commit was 4 months ago).

I don't have the knowledge to fix/improve (I'm not a Java/Coffee developer at all).

Thanks for your suggestions.

Damien
