### ISSUE TITLE
Association with .tpl file by default

### ISSUE THREAD

**Issue by littlbr** [martin-damien/language-smarty-php#5]
Hi,

When opening a .tpl file, the syntax is set to HTML and I need to set it back to Smarty on each file.
Any idea on how to force the source.smarty on all .tpl file upon creation or first opening?

Thanks for the plugin!

**Comment by martin-damien** [comment]
Hi,

I just checked opening a tpl file and HTML was selected too. This is new (as far as I remember, tpl files were opened as smarty files before). I understand that this could be annoying.

I will take a look as soon as possible.

**Comment by littlbr** [comment]
Thanks Damien ! Let me know if I can beta test anything for you.

2015-02-26 9:43 GMT+01:00 MARTIN Damien <notifications@github.com>:

**Comment by martin-damien** [comment]
Hi,

I have a solution for you: You can force grammar usage for file extension in `init.coffee`.

Add this piece of code in `init.coffee`:

```coffeescript
path = require 'path'

atom.workspace.observeTextEditors (editor) ->
    if path.extname(editor.getPath()) == ".tpl"
        editor.setGrammar(atom.grammars.grammarForScopeName('source.smarty'))
```

This will force the *Smarty* grammar for all the "tpl" files.

**Comment by littlbr** [comment]
Hey, I've tested your solution and it works perfectly ! Thanks a lot mate !

2015-02-27 23:08 GMT+01:00 MARTIN Damien <notifications@github.com>:
