### ISSUE TITLE
No highlight below {literal}

### ISSUE THREAD

**Issue by llagerlof** [martin-damien/language-smarty-php#6]
This plugin ignores the highlight between {literal} and {/literal}. This is normal?

look:
![ksggoeg 1](https://cloud.githubusercontent.com/assets/193798/8386903/7c7ae50a-1c2a-11e5-8d80-e452abcb3779.png)

Thanks.

**Comment by martin-damien** [comment]
The plugin is a port of the Textmate plugin generated by Atom and it looks like it was not supported.
I will try to add it when I can.

**Comment by saddy123** [comment]
hey martin, 
maybe you can steal the feature from this: https://atom.io/packages/language-smarty
plugin? 
I dont use it because i make used with the general color scheme of your plugin.

**Comment by martin-damien** [comment]
Hi there,

I inform you that I will delete this package soon.

I don't have the knowledge and the time to fix it (it was an automatic conversion from sublime package).

You should use https://atom.io/packages/language-smarty package, it looks to be maintained (last commit was 4 months ago).

Thanks for reporting this issue.

Damien
