### ISSUE TITLE
syntax highlighting gets hung up on single quotes

### ISSUE THREAD

**Issue by sanstream** [martin-damien/language-smarty-php#7]
Hi,

The syntax highlighting thinks that in a string like this:
```
Chambres d'hôtes
```
A new string starts at the quotation mark, but it does not.

**Comment by martin-damien** [comment]
Hello @sanstream ,

It is one year I haven't updated this package. The mainly reasons are:

- I don't use it myself (I work with Twig now)
- I don't have the knowledge to maintain it correctly

I'm sorry to say that I will delete this package soon (I just unpublished it from Atom packages).

You should use https://atom.io/packages/language-smarty package, it looks to be maintained (last commit was 4 months ago).

Kind regards

Damien
